# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=50)),
                ('nick_name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=30)),
            ],
        ),
    ]
